language: cpp

matrix:
  include:
    - env: BUILD_TYPE=Debug   CXX_STANDARD=11
      compiler: clang
      sudo: true
      addons:
        apt:
          packages:
            - bison

    - env: BUILD_TYPE=Debug   CXX_STANDARD=11
      compiler: gcc
      sudo: true
      addons:
        apt:
          packages:
            - bison

    - env: BUILD_TYPE=Release CXX_STANDARD=17
      compiler: clang
      dist: bionic

    - env: BUILD_TYPE=Release CXX_STANDARD=17
      compiler: gcc
      dist: bionic

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_STANDARD=$CXX_STANDARD
  - cmake --build . -- -j4
  - ctest -j4
